/* Auto-generated by genmsg_cpp for file /home/olivier/ros_workspace/naos_localization/msg/Odometry.msg */
#ifndef NAOS_LOCALIZATION_MESSAGE_ODOMETRY_H
#define NAOS_LOCALIZATION_MESSAGE_ODOMETRY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace naos_localization
{
template <class ContainerAllocator>
struct Odometry_ {
  typedef Odometry_<ContainerAllocator> Type;

  Odometry_()
  : header()
  , x(0.0)
  , y(0.0)
  , vx(0.0)
  , vy(0.0)
  {
  }

  Odometry_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , vx(0.0)
  , vy(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _vx_type;
  float vx;

  typedef float _vy_type;
  float vy;


  typedef boost::shared_ptr< ::naos_localization::Odometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naos_localization::Odometry_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Odometry
typedef  ::naos_localization::Odometry_<std::allocator<void> > Odometry;

typedef boost::shared_ptr< ::naos_localization::Odometry> OdometryPtr;
typedef boost::shared_ptr< ::naos_localization::Odometry const> OdometryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::naos_localization::Odometry_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::naos_localization::Odometry_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace naos_localization

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::naos_localization::Odometry_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::naos_localization::Odometry_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::naos_localization::Odometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "73b81bc331e6b03fe46669de7556c5d4";
  }

  static const char* value(const  ::naos_localization::Odometry_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x73b81bc331e6b03fULL;
  static const uint64_t static_value2 = 0xe46669de7556c5d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::naos_localization::Odometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "naos_localization/Odometry";
  }

  static const char* value(const  ::naos_localization::Odometry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::naos_localization::Odometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
Header header\n\
\n\
# Position\n\
float32 x\n\
float32 y\n\
\n\
# Velocity\n\
float32 vx\n\
float32 vy\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::naos_localization::Odometry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::naos_localization::Odometry_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::naos_localization::Odometry_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::naos_localization::Odometry_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.vx);
    stream.next(m.vy);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Odometry_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naos_localization::Odometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::naos_localization::Odometry_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NAOS_LOCALIZATION_MESSAGE_ODOMETRY_H

