/* Auto-generated by genmsg_cpp for file /home/olivier/ros_workspace/nao_behavior_tree/msg/Bearing.msg */
#ifndef NAO_BEHAVIOR_TREE_MESSAGE_BEARING_H
#define NAO_BEHAVIOR_TREE_MESSAGE_BEARING_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace nao_behavior_tree
{
template <class ContainerAllocator>
struct Bearing_ {
  typedef Bearing_<ContainerAllocator> Type;

  Bearing_()
  : header()
  , robotDetected(false)
  , absolute(0.0)
  , relative(0.0)
  {
  }

  Bearing_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , robotDetected(false)
  , absolute(0.0)
  , relative(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _robotDetected_type;
  uint8_t robotDetected;

  typedef float _absolute_type;
  float absolute;

  typedef float _relative_type;
  float relative;


  typedef boost::shared_ptr< ::nao_behavior_tree::Bearing_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_behavior_tree::Bearing_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Bearing
typedef  ::nao_behavior_tree::Bearing_<std::allocator<void> > Bearing;

typedef boost::shared_ptr< ::nao_behavior_tree::Bearing> BearingPtr;
typedef boost::shared_ptr< ::nao_behavior_tree::Bearing const> BearingConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nao_behavior_tree::Bearing_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nao_behavior_tree::Bearing_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nao_behavior_tree

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::Bearing_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::Bearing_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_behavior_tree::Bearing_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f889ef5163854f388ed046e2be75353c";
  }

  static const char* value(const  ::nao_behavior_tree::Bearing_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf889ef5163854f38ULL;
  static const uint64_t static_value2 = 0x8ed046e2be75353cULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_behavior_tree::Bearing_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/Bearing";
  }

  static const char* value(const  ::nao_behavior_tree::Bearing_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_behavior_tree::Bearing_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Bearing values\n\
\n\
Header header\n\
\n\
bool robotDetected\n\
\n\
float32 absolute\n\
float32 relative\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::nao_behavior_tree::Bearing_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::nao_behavior_tree::Bearing_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::nao_behavior_tree::Bearing_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_behavior_tree::Bearing_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.robotDetected);
    stream.next(m.absolute);
    stream.next(m.relative);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Bearing_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_behavior_tree::Bearing_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nao_behavior_tree::Bearing_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robotDetected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robotDetected);
    s << indent << "absolute: ";
    Printer<float>::stream(s, indent + "  ", v.absolute);
    s << indent << "relative: ";
    Printer<float>::stream(s, indent + "  ", v.relative);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NAO_BEHAVIOR_TREE_MESSAGE_BEARING_H

