/* Auto-generated by genmsg_cpp for file /home/olivier/ros_workspace/nao_behavior_tree/msg/Velocity.msg */
#ifndef NAO_BEHAVIOR_TREE_MESSAGE_VELOCITY_H
#define NAO_BEHAVIOR_TREE_MESSAGE_VELOCITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace nao_behavior_tree
{
template <class ContainerAllocator>
struct Velocity_ {
  typedef Velocity_<ContainerAllocator> Type;

  Velocity_()
  : header()
  , norm(0.0)
  , theta(0.0)
  {
  }

  Velocity_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , norm(0.0)
  , theta(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _norm_type;
  float norm;

  typedef float _theta_type;
  float theta;


  typedef boost::shared_ptr< ::nao_behavior_tree::Velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_behavior_tree::Velocity_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Velocity
typedef  ::nao_behavior_tree::Velocity_<std::allocator<void> > Velocity;

typedef boost::shared_ptr< ::nao_behavior_tree::Velocity> VelocityPtr;
typedef boost::shared_ptr< ::nao_behavior_tree::Velocity const> VelocityConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nao_behavior_tree::Velocity_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nao_behavior_tree::Velocity_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nao_behavior_tree

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::Velocity_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::Velocity_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_behavior_tree::Velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1b7fe3312b176a60126a2063c0e05cd6";
  }

  static const char* value(const  ::nao_behavior_tree::Velocity_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1b7fe3312b176a60ULL;
  static const uint64_t static_value2 = 0x126a2063c0e05cd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_behavior_tree::Velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/Velocity";
  }

  static const char* value(const  ::nao_behavior_tree::Velocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_behavior_tree::Velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
Header header\n\
\n\
# Velocity\n\
float32 norm\n\
float32 theta\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::nao_behavior_tree::Velocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::nao_behavior_tree::Velocity_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::nao_behavior_tree::Velocity_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_behavior_tree::Velocity_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.norm);
    stream.next(m.theta);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Velocity_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_behavior_tree::Velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nao_behavior_tree::Velocity_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "norm: ";
    Printer<float>::stream(s, indent + "  ", v.norm);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NAO_BEHAVIOR_TREE_MESSAGE_VELOCITY_H

