/* Auto-generated by genmsg_cpp for file /home/olivier/ros_workspace/nao_behavior_tree/srv/ArmReadyBT.srv */
#ifndef NAO_BEHAVIOR_TREE_SERVICE_ARMREADYBT_H
#define NAO_BEHAVIOR_TREE_SERVICE_ARMREADYBT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace nao_behavior_tree
{
template <class ContainerAllocator>
struct ArmReadyBTRequest_ {
  typedef ArmReadyBTRequest_<ContainerAllocator> Type;

  ArmReadyBTRequest_()
  : NAO(0)
  , arm(0)
  {
  }

  ArmReadyBTRequest_(const ContainerAllocator& _alloc)
  : NAO(0)
  , arm(0)
  {
  }

  typedef int32_t _NAO_type;
  int32_t NAO;

  typedef int32_t _arm_type;
  int32_t arm;


  typedef boost::shared_ptr< ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ArmReadyBTRequest
typedef  ::nao_behavior_tree::ArmReadyBTRequest_<std::allocator<void> > ArmReadyBTRequest;

typedef boost::shared_ptr< ::nao_behavior_tree::ArmReadyBTRequest> ArmReadyBTRequestPtr;
typedef boost::shared_ptr< ::nao_behavior_tree::ArmReadyBTRequest const> ArmReadyBTRequestConstPtr;


template <class ContainerAllocator>
struct ArmReadyBTResponse_ {
  typedef ArmReadyBTResponse_<ContainerAllocator> Type;

  ArmReadyBTResponse_()
  {
  }

  ArmReadyBTResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ArmReadyBTResponse
typedef  ::nao_behavior_tree::ArmReadyBTResponse_<std::allocator<void> > ArmReadyBTResponse;

typedef boost::shared_ptr< ::nao_behavior_tree::ArmReadyBTResponse> ArmReadyBTResponsePtr;
typedef boost::shared_ptr< ::nao_behavior_tree::ArmReadyBTResponse const> ArmReadyBTResponseConstPtr;

struct ArmReadyBT
{

typedef ArmReadyBTRequest Request;
typedef ArmReadyBTResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ArmReadyBT
} // namespace nao_behavior_tree

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d090919db246d41a7da74bd56eadc6ec";
  }

  static const char* value(const  ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd090919db246d41aULL;
  static const uint64_t static_value2 = 0x7da74bd56eadc6ecULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/ArmReadyBTRequest";
  }

  static const char* value(const  ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 NAO\n\
int32 arm\n\
\n\
";
  }

  static const char* value(const  ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/ArmReadyBTResponse";
  }

  static const char* value(const  ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.NAO);
    stream.next(m.arm);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ArmReadyBTRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ArmReadyBTResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<nao_behavior_tree::ArmReadyBT> {
  static const char* value() 
  {
    return "d090919db246d41a7da74bd56eadc6ec";
  }

  static const char* value(const nao_behavior_tree::ArmReadyBT&) { return value(); } 
};

template<>
struct DataType<nao_behavior_tree::ArmReadyBT> {
  static const char* value() 
  {
    return "nao_behavior_tree/ArmReadyBT";
  }

  static const char* value(const nao_behavior_tree::ArmReadyBT&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d090919db246d41a7da74bd56eadc6ec";
  }

  static const char* value(const nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/ArmReadyBT";
  }

  static const char* value(const nao_behavior_tree::ArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d090919db246d41a7da74bd56eadc6ec";
  }

  static const char* value(const nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/ArmReadyBT";
  }

  static const char* value(const nao_behavior_tree::ArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // NAO_BEHAVIOR_TREE_SERVICE_ARMREADYBT_H

