/* Auto-generated by genmsg_cpp for file /home/olivier/ros_workspace/nao_behavior_tree/srv/GetArmReadyBT.srv */
#ifndef NAO_BEHAVIOR_TREE_SERVICE_GETARMREADYBT_H
#define NAO_BEHAVIOR_TREE_SERVICE_GETARMREADYBT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace nao_behavior_tree
{
template <class ContainerAllocator>
struct GetArmReadyBTRequest_ {
  typedef GetArmReadyBTRequest_<ContainerAllocator> Type;

  GetArmReadyBTRequest_()
  : NAO(0)
  {
  }

  GetArmReadyBTRequest_(const ContainerAllocator& _alloc)
  : NAO(0)
  {
  }

  typedef int32_t _NAO_type;
  int32_t NAO;


  typedef boost::shared_ptr< ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetArmReadyBTRequest
typedef  ::nao_behavior_tree::GetArmReadyBTRequest_<std::allocator<void> > GetArmReadyBTRequest;

typedef boost::shared_ptr< ::nao_behavior_tree::GetArmReadyBTRequest> GetArmReadyBTRequestPtr;
typedef boost::shared_ptr< ::nao_behavior_tree::GetArmReadyBTRequest const> GetArmReadyBTRequestConstPtr;


template <class ContainerAllocator>
struct GetArmReadyBTResponse_ {
  typedef GetArmReadyBTResponse_<ContainerAllocator> Type;

  GetArmReadyBTResponse_()
  : arm(0)
  {
  }

  GetArmReadyBTResponse_(const ContainerAllocator& _alloc)
  : arm(0)
  {
  }

  typedef int32_t _arm_type;
  int32_t arm;


  typedef boost::shared_ptr< ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetArmReadyBTResponse
typedef  ::nao_behavior_tree::GetArmReadyBTResponse_<std::allocator<void> > GetArmReadyBTResponse;

typedef boost::shared_ptr< ::nao_behavior_tree::GetArmReadyBTResponse> GetArmReadyBTResponsePtr;
typedef boost::shared_ptr< ::nao_behavior_tree::GetArmReadyBTResponse const> GetArmReadyBTResponseConstPtr;

struct GetArmReadyBT
{

typedef GetArmReadyBTRequest Request;
typedef GetArmReadyBTResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetArmReadyBT
} // namespace nao_behavior_tree

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "90eb40daba5b4c8c59365cf231e3cb25";
  }

  static const char* value(const  ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x90eb40daba5b4c8cULL;
  static const uint64_t static_value2 = 0x59365cf231e3cb25ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/GetArmReadyBTRequest";
  }

  static const char* value(const  ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 NAO\n\
\n\
";
  }

  static const char* value(const  ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "473ea5c8ff1423062423fdc15445f0b5";
  }

  static const char* value(const  ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x473ea5c8ff142306ULL;
  static const uint64_t static_value2 = 0x2423fdc15445f0b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/GetArmReadyBTResponse";
  }

  static const char* value(const  ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 arm\n\
\n\
\n\
";
  }

  static const char* value(const  ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.NAO);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetArmReadyBTRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.arm);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetArmReadyBTResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<nao_behavior_tree::GetArmReadyBT> {
  static const char* value() 
  {
    return "0e5c583016bfad7605d4c06a7dca15b3";
  }

  static const char* value(const nao_behavior_tree::GetArmReadyBT&) { return value(); } 
};

template<>
struct DataType<nao_behavior_tree::GetArmReadyBT> {
  static const char* value() 
  {
    return "nao_behavior_tree/GetArmReadyBT";
  }

  static const char* value(const nao_behavior_tree::GetArmReadyBT&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0e5c583016bfad7605d4c06a7dca15b3";
  }

  static const char* value(const nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/GetArmReadyBT";
  }

  static const char* value(const nao_behavior_tree::GetArmReadyBTRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0e5c583016bfad7605d4c06a7dca15b3";
  }

  static const char* value(const nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_behavior_tree/GetArmReadyBT";
  }

  static const char* value(const nao_behavior_tree::GetArmReadyBTResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // NAO_BEHAVIOR_TREE_SERVICE_GETARMREADYBT_H

