; Auto-generated. Do not edit!


(cl:in-package nao_behavior_tree-msg)


;//! \htmlinclude ROSFeedback.msg.html

(cl:defclass <ROSFeedback> (roslisp-msg-protocol:ros-message)
  ((FEEDBACK_
    :reader FEEDBACK_
    :initarg :FEEDBACK_
    :type cl:integer
    :initform 0))
)

(cl:defclass ROSFeedback (<ROSFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ROSFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ROSFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nao_behavior_tree-msg:<ROSFeedback> is deprecated: use nao_behavior_tree-msg:ROSFeedback instead.")))

(cl:ensure-generic-function 'FEEDBACK_-val :lambda-list '(m))
(cl:defmethod FEEDBACK_-val ((m <ROSFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nao_behavior_tree-msg:FEEDBACK_-val is deprecated.  Use nao_behavior_tree-msg:FEEDBACK_ instead.")
  (FEEDBACK_ m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ROSFeedback>) ostream)
  "Serializes a message object of type '<ROSFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'FEEDBACK_)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ROSFeedback>) istream)
  "Deserializes a message object of type '<ROSFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'FEEDBACK_) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ROSFeedback>)))
  "Returns string type for a message object of type '<ROSFeedback>"
  "nao_behavior_tree/ROSFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ROSFeedback)))
  "Returns string type for a message object of type 'ROSFeedback"
  "nao_behavior_tree/ROSFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ROSFeedback>)))
  "Returns md5sum for a message object of type '<ROSFeedback>"
  "fd37041da8d6188d42b48d39e7cc0be0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ROSFeedback)))
  "Returns md5sum for a message object of type 'ROSFeedback"
  "fd37041da8d6188d42b48d39e7cc0be0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ROSFeedback>)))
  "Returns full string definition for message of type '<ROSFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 FEEDBACK_~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ROSFeedback)))
  "Returns full string definition for message of type 'ROSFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 FEEDBACK_~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ROSFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ROSFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ROSFeedback
    (cl:cons ':FEEDBACK_ (FEEDBACK_ msg))
))
