; Auto-generated. Do not edit!


(cl:in-package nao_behavior_tree-msg)


;//! \htmlinclude ROSGoal.msg.html

(cl:defclass <ROSGoal> (roslisp-msg-protocol:ros-message)
  ((GOAL_
    :reader GOAL_
    :initarg :GOAL_
    :type cl:integer
    :initform 0))
)

(cl:defclass ROSGoal (<ROSGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ROSGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ROSGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nao_behavior_tree-msg:<ROSGoal> is deprecated: use nao_behavior_tree-msg:ROSGoal instead.")))

(cl:ensure-generic-function 'GOAL_-val :lambda-list '(m))
(cl:defmethod GOAL_-val ((m <ROSGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nao_behavior_tree-msg:GOAL_-val is deprecated.  Use nao_behavior_tree-msg:GOAL_ instead.")
  (GOAL_ m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ROSGoal>) ostream)
  "Serializes a message object of type '<ROSGoal>"
  (cl:let* ((signed (cl:slot-value msg 'GOAL_)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ROSGoal>) istream)
  "Deserializes a message object of type '<ROSGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'GOAL_) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ROSGoal>)))
  "Returns string type for a message object of type '<ROSGoal>"
  "nao_behavior_tree/ROSGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ROSGoal)))
  "Returns string type for a message object of type 'ROSGoal"
  "nao_behavior_tree/ROSGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ROSGoal>)))
  "Returns md5sum for a message object of type '<ROSGoal>"
  "c7b14ba257795c9c39554f76f2fa8ca0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ROSGoal)))
  "Returns md5sum for a message object of type 'ROSGoal"
  "c7b14ba257795c9c39554f76f2fa8ca0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ROSGoal>)))
  "Returns full string definition for message of type '<ROSGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 GOAL_~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ROSGoal)))
  "Returns full string definition for message of type 'ROSGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 GOAL_~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ROSGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ROSGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ROSGoal
    (cl:cons ':GOAL_ (GOAL_ msg))
))
