; Auto-generated. Do not edit!


(cl:in-package nao_behavior_tree-msg)


;//! \htmlinclude ROSResult.msg.html

(cl:defclass <ROSResult> (roslisp-msg-protocol:ros-message)
  ((RESULT_
    :reader RESULT_
    :initarg :RESULT_
    :type cl:integer
    :initform 0))
)

(cl:defclass ROSResult (<ROSResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ROSResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ROSResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nao_behavior_tree-msg:<ROSResult> is deprecated: use nao_behavior_tree-msg:ROSResult instead.")))

(cl:ensure-generic-function 'RESULT_-val :lambda-list '(m))
(cl:defmethod RESULT_-val ((m <ROSResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nao_behavior_tree-msg:RESULT_-val is deprecated.  Use nao_behavior_tree-msg:RESULT_ instead.")
  (RESULT_ m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ROSResult>) ostream)
  "Serializes a message object of type '<ROSResult>"
  (cl:let* ((signed (cl:slot-value msg 'RESULT_)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ROSResult>) istream)
  "Deserializes a message object of type '<ROSResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'RESULT_) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ROSResult>)))
  "Returns string type for a message object of type '<ROSResult>"
  "nao_behavior_tree/ROSResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ROSResult)))
  "Returns string type for a message object of type 'ROSResult"
  "nao_behavior_tree/ROSResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ROSResult>)))
  "Returns md5sum for a message object of type '<ROSResult>"
  "56059e83f8ae01dfef47ef22668077d1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ROSResult)))
  "Returns md5sum for a message object of type 'ROSResult"
  "56059e83f8ae01dfef47ef22668077d1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ROSResult>)))
  "Returns full string definition for message of type '<ROSResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 RESULT_~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ROSResult)))
  "Returns full string definition for message of type 'ROSResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 RESULT_~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ROSResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ROSResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ROSResult
    (cl:cons ':RESULT_ (RESULT_ msg))
))
