/* Auto-generated by genmsg_cpp for file /home/olivier/ros_workspace/first_approaches/msg/PosImage.msg */
#ifndef FIRST_APPROACHES_MESSAGE_POSIMAGE_H
#define FIRST_APPROACHES_MESSAGE_POSIMAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace first_approaches
{
template <class ContainerAllocator>
struct PosImage_ {
  typedef PosImage_<ContainerAllocator> Type;

  PosImage_()
  : x(0)
  , y(0)
  , height(0)
  , width(0)
  , depth(0.0)
  {
  }

  PosImage_(const ContainerAllocator& _alloc)
  : x(0)
  , y(0)
  , height(0)
  , width(0)
  , depth(0.0)
  {
  }

  typedef int32_t _x_type;
  int32_t x;

  typedef int32_t _y_type;
  int32_t y;

  typedef int32_t _height_type;
  int32_t height;

  typedef int32_t _width_type;
  int32_t width;

  typedef float _depth_type;
  float depth;


  typedef boost::shared_ptr< ::first_approaches::PosImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_approaches::PosImage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PosImage
typedef  ::first_approaches::PosImage_<std::allocator<void> > PosImage;

typedef boost::shared_ptr< ::first_approaches::PosImage> PosImagePtr;
typedef boost::shared_ptr< ::first_approaches::PosImage const> PosImageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::first_approaches::PosImage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::first_approaches::PosImage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace first_approaches

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::first_approaches::PosImage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::first_approaches::PosImage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::first_approaches::PosImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cf0beac2e7204b108e4d905cfbc48a56";
  }

  static const char* value(const  ::first_approaches::PosImage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcf0beac2e7204b10ULL;
  static const uint64_t static_value2 = 0x8e4d905cfbc48a56ULL;
};

template<class ContainerAllocator>
struct DataType< ::first_approaches::PosImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "first_approaches/PosImage";
  }

  static const char* value(const  ::first_approaches::PosImage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::first_approaches::PosImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 x\n\
int32 y\n\
int32 height\n\
int32 width\n\
float32 depth\n\
\n\
";
  }

  static const char* value(const  ::first_approaches::PosImage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::first_approaches::PosImage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::first_approaches::PosImage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.height);
    stream.next(m.width);
    stream.next(m.depth);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PosImage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_approaches::PosImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::first_approaches::PosImage_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FIRST_APPROACHES_MESSAGE_POSIMAGE_H

